server:
  port: 9000

spring:
  application:
    name: sub-board-article-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb   # MySQL 연결 URL
    username: ${MYSQL_USERNAME}  # 환경 변수로 사용자명
    password: ${MYSQL_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none